=== Coornh/homeassistant-powercalc/profile_library/model_schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "description": "model.json describes a number of devices, typically lights, for use within the HomeAssistant Powercalc extension.",
  "type": "object",
  "required": [
    "name",
    "measure_method",
    "measure_device",
    "calculation_strategy"
  ],
  "properties": {
    "created_at": {
      "type": "string",
      "format": "date-time",
      "description": "Creation date of the profile"
    },
    "name": {
      "type": "string",
      "description": "The full name"
    },
    "description": {
      "type": "string",
      "description": "A short description of the device"
    },
    "standby_power": {
      "type": "number",
      "minimum": 0.05,
      "description": "Power draw when the device is turned off. When you are not able to measure set to 0.4 for lights"
    },
    "standby_power_on": {
      "type": "number",
      "minimum": 0.05,
      "description": "Power draw when the device is turned on."
    },
    "calculation_strategy": {
      "type": "string",
      "enum": [
        "lut",
        "linear",
        "fixed",
        "multi_switch",
        "composite"
      ],
      "description": "Supported calculation strategies"
    },
    "measure_method": {
      "type": "string",
      "enum": [
        "manual",
        "script"
      ],
      "description": "How the device was measured"
    },
    "measure_device": {
      "type": "string",
      "description": "Device which was used to measure"
    },
    "measure_device_firmware": {
      "type": "string",
      "description": "Firmware version of the device used to measure"
    },
    "measure_description": {
      "type": "string",
      "description": "Add more information about how you measured the device or any remarks"
    },
    "measure_settings": {
      "type": "object",
      "description": "Settings used for measure script"
    },
    "linked_lut": {
      "type": "string",
      "description": "Use LUT data files from another model"
    },
    "device_type": {
      "type": "string",
      "enum": [
        "camera",
        "cover",
        "light",
        "printer",
        "smart_dimmer",
        "smart_switch",
        "smart_speaker",
        "network",
        "vacuum_robot"
      ],
      "description": "Type of device"
    },
    "calculation_enabled_condition": {
      "type": "string",
      "description": "Template which can be evaluated."
    },
    "aliases": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "description": "Aliases for this model"
    },
    "linear_config": {
      "type": "object",
      "description": "Configuration for linear calculation strategy",
      "properties": {
        "min_power": {
          "type": "number"
        },
        "max_power": {
          "type": "number"
        },
        "calibrate": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      }
    },
    "fixed_config": {
      "type": "object",
      "description": "Configuration for fixed calculation strategy",
      "properties": {
        "power": {
          "type": "number"
        },
        "states_power": {
          "type": "object",
          "description": "A dict of state attributes and the power. See https://github.com/bramstroker/homeassistant-powercalc#power-per-state.",
          "properties": {
            "idle": {
              "type": [
                "number",
                "string"
              ]
            },
            "playing": {
              "type": [
                "number",
                "string"
              ]
            },
            "paused": {
              "type": [
                "number",
                "string"
              ]
            },
            "off": {
              "type": [
                "number",
                "string"
              ]
            },
            "unavailable": {
              "type": [
                "number",
                "string"
              ]
            }
          },
          "additionalProperties": {
            "type": [
              "number",
              "string"
            ]
          }
        }
      }
    },
    "playbook_config": {
      "type": "object",
      "description": "Configuration for playbook calculation strategy",
      "properties": {
        "playbooks": {
          "type": "object",
          "additionalProperties": {
            "type": "string"
          },
          "description": "Key-value pairs where the key is a playbook ID and the value is the filename."
        },
        "autostart": {
          "type": "string",
          "description": "The playbook ID to autostart."
        },
        "repeat": {
          "type": "boolean",
          "description": "Indicates if the playbook should repeat."
        },
        "state_trigger": {
          "type": "object",
          "additionalProperties": {
            "type": "string"
          },
          "description": "Start given playbook when entity state changes to given value."
        }
      },
      "required": [
        "playbooks"
      ]
    },
    "composite_config": {
      "type": "array",
      "description": "Configuration for composite calculation strategy",
      "items": {
        "type": "object",
        "properties": {
          "condition": {
            "$ref": "#/definitions/condition"
          }
        }
      }
    },
    "config_flow_discovery_remarks": {
      "type": "string",
      "description": "Some remarks to show in the GUI config flow on first step of discovery"
    },
    "sensor_config": {
      "type": "object",
      "description": "Sensor configuration options. See the README"
    },
    "sub_profile_select": {
      "type": "object",
      "description": "Configuration to automatically select a sub profile",
      "required": [
        "default",
        "matchers"
      ],
      "properties": {
        "default": {
          "type": "string",
          "description": "Default profile to select when non of the matchers apply"
        },
        "matchers": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "type": {
                "enum": [
                  "attribute",
                  "entity_id",
                  "entity_state",
                  "integration"
                ]
              },
              "attribute": {
                "type": "string"
              },
              "map": {
                "type": "object"
              },
              "pattern": {
                "type": "string"
              },
              "profile": {
                "type": "string"
              },
              "integration": {
                "type": "string"
              }
            },
            "required": [
              "type"
            ]
          },
          "description": "List of matchers which will be checked"
        }
      }
    }
  },
  "definitions": {
    "condition": {
      "type": "object",
      "properties": {
        "condition": {
          "type": "string",
          "enum": [
            "and",
            "or",
            "state",
            "numeric_state",
            "template"
          ]
        },
        "conditions": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/condition"
          }
        }
      },
      "additionalProperties": true
    }
  }
}

=== Coornh/homeassistant-powercalc/profile_library/calex/G95 Gold/model.json
{
  "calculation_strategy": "lut",
  "created_at": "2025-04-28T23:34:57.359526",
  "measure_description": "Measured with utils/measure script",
  "measure_device": "Shelly Plus Plug S",
  "measure_method": "script",
  "measure_settings": {
    "SAMPLE_COUNT": 2,
    "SLEEP_TIME": 3,
    "VERSION": "v1.17.11:docker"
  },
  "name": "G95Gold",
  "standby_power": 0.61
}

=== Coornh/homeassistant-powercalc/profile_library/signify/1743730P7/model.json
{
  "calculation_strategy": "lut",
  "created_at": "2025-03-13T20:09:51.989491",
  "measure_description": "Measured with utils/measure script",
  "measure_device": "TP-Link Kasa HS110",
  "measure_method": "script",
  "measure_settings": {
    "SAMPLE_COUNT": 2,
    "SLEEP_TIME": 3,
    "VERSION": "v1.17.9:docker"
  },
  "name": "Hue Calla Large Outdoor Pedestal",
  "standby_power": 0.35
}

=== Coornh/homeassistant-powercalc/profile_library/tuya/CK-BL702-AL-01/model.json
{
  "calculation_strategy": "lut",
  "created_at": "2025-01-23T13:08:49.501748",
  "measure_description": "Measured with utils/measure script",
  "measure_device": "TP-Link HS110",
  "measure_method": "script",
  "measure_settings": {
    "SAMPLE_COUNT": 2,
    "SLEEP_TIME": 3,
    "VERSION": "v1.17.2:docker"
  },
  "name": "CK-BL702-AL-01",
  "standby_power": 0.44
}

=== Coornh/homeassistant-powercalc/profile_library/cree/CMA19-60W-AL-9TW-GL/model.json
{
  "calculation_strategy": "lut",
  "created_at": "2024-12-08T14:20:08.100497",
  "measure_description": "Measured with utils/measure script",
  "measure_device": "Shelly PM Mini Gen3",
  "measure_method": "script",
  "measure_settings": {
    "SAMPLE_COUNT": 2,
    "SLEEP_TIME": 3,
    "VERSION": "master"
  },
  "name": "Treatlife Smart Color Changing Light Bulb 9W 800LM",
  "standby_power": 0.55
}

=== Coornh/homeassistant-powercalc/profile_library/google/Home Hub Max/model.json
{
  "calculation_enabled_condition": "{{ is_state('[[entity]]', 'playing') }}",
  "calculation_strategy": "linear",
  "created_at": "2025-01-07T12:48:09.002487",
  "device_type": "smart_speaker",
  "linear_config": {
    "calibrate": [
      "10 -> 7.0",
      "20 -> 7.0",
      "30 -> 7.0",
      "40 -> 6.2",
      "50 -> 5.4",
      "60 -> 6.0",
      "70 -> 6.0",
      "80 -> 7.2",
      "90 -> 8.6",
      "100 -> 10.4",
      "0 -> 5.4"
    ]
  },
  "measure_description": "Measured with utils/measure script",
  "measure_device": "SmartThings F-APP-UK-V2",
  "measure_method": "script",
  "measure_settings": {
    "SAMPLE_COUNT": 2,
    "SLEEP_TIME": 3,
    "VERSION": "v1.16.7:docker"
  },
  "name": "Google Home Hub Max",
  "standby_power": 3.0
}

=== Coornh/homeassistant-powercalc/profile_library/paulmann licht/50396/model.json
{
  "calculation_strategy": "lut",
  "created_at": "2024-11-15T11:59:34.923133",
  "measure_description": "Measured with utils/measure script",
  "measure_device": "TS011F",
  "measure_method": "script",
  "measure_settings": {
    "SAMPLE_COUNT": 2,
    "SLEEP_TIME": 3,
    "VERSION": "v1.15.4:docker"
  },
  "name": "50396",
  "standby_power": 0
}

=== Coornh/homeassistant-powercalc/profile_library/amazon/RS03QR/model.json
{
  "calculation_enabled_condition": "{{ is_state('[[entity]]', 'playing') }}",
  "calculation_strategy": "linear",
  "created_at": "2025-04-30T20:17:58.225009",
  "device_type": "smart_speaker",
  "linear_config": {
    "calibrate": [
      "10 -> 1.93",
      "20 -> 1.97",
      "30 -> 2.09",
      "40 -> 2.07",
      "50 -> 2.13",
      "60 -> 2.49",
      "70 -> 2.64",
      "80 -> 2.29",
      "90 -> 2.19",
      "100 -> 2.19",
      "0 -> 1.77"
    ]
  },
  "measure_description": "Measured with utils/measure script",
  "measure_device": "Shelly PM mini Gen3",
  "measure_method": "script",
  "measure_settings": {
    "SAMPLE_COUNT": 2,
    "SLEEP_TIME": 3,
    "VERSION": "v1.17.11:docker"
  },
  "name": "Amazon Alexa Echo Dot Gen 2",
  "standby_power": 1.8
}

=== Coornh/homeassistant-powercalc/tests/testing_config/powercalc_profiles/composite/model.json
{
  "name": "IKEA Control outlet",
  "standby_power": 0.52,
  "standby_power_on": 0.82,
  "measure_method": "manual",
  "measure_device": "IKEA Control outlet",
  "device_type": "smart_switch",
  "calculation_strategy": "composite",
  "composite_config": [
    {
      "condition": {
        "condition_type": "state",
        "entity_id": "switch.ikea_control_outlet"
      },
      "fixed_config": {
        "power": 0.82
      }
    },
    {
      "fixed_config": {
        "power": 0.52
      }
    }
  ]
}
